In [1]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss, accuracy_score

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('insurance_prediction_training.csv')

In [4]:
df.head()

,id,region,village,age,agpop,rice_inc,ricearea_2010,general_trust,educ,educ_good,male,disaster_loss,disaster_yes,risk_averse,literacy,age_missing,agpop_missing,rice_inc_missing,ricearea_2010_missing,disaster_loss_missing,educ_missing,male_missing,literacy_missing,takeup
0,1,1,21,54,2,20,2.4,1,2.0,1,1,0,0,0.4,1,0,0,0,0,1,0,0,0,1
1,2,1,21,73,2,100,2.3,1,1.0,0,1,0,0,0.0,1,0,0,0,0,1,0,0,0,1
2,3,1,21,72,10,80,12.0,1,1.0,0,1,0,0,0.0,1,0,0,0,0,1,0,0,0,1
3,4,1,21,43,4,20,4.0,1,2.0,1,1,0,1,0.0,1,0,0,0,0,1,0,0,0,0
4,5,1,21,63,6,90,14.0,1,1.0,0,1,0,1,0.0,1,0,0,0,0,1,0,0,0,0

In [5]:
df.isna().sum()

id                        0
region                    0
village                   0
age                       0
agpop                     0
rice_inc                  0
ricearea_2010             0
general_trust             0
educ                     23
educ_good                 0
male                      0
disaster_loss             0
disaster_yes              0
risk_averse               0
literacy                  0
age_missing               0
agpop_missing             0
rice_inc_missing          0
ricearea_2010_missing     0
disaster_loss_missing     0
educ_missing              0
male_missing              0
literacy_missing          0
takeup                    0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
X = df.drop(['takeup'], axis = 1)
y = df.takeup

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)

In [9]:
def one_hot_encode(data, col):
    encoded_data = pd.get_dummies(data, columns=[col])
    return encoded_data

In [10]:
X_train = one_hot_encode(X_train, 'region')

In [11]:
#X_train = one_hot_encode(X_train, 'village')

In [12]:
X_train.head()

,id,village,age,agpop,rice_inc,ricearea_2010,general_trust,educ,educ_good,male,disaster_loss,disaster_yes,risk_averse,literacy,age_missing,agpop_missing,rice_inc_missing,ricearea_2010_missing,disaster_loss_missing,educ_missing,male_missing,literacy_missing,region_1,region_2,region_3
2781,2782,21,41,4,40,7.0,1,2.0,1,1,0,0,0.0,1,0,0,0,0,1,0,0,0,1,0,0
2524,2525,45,35,6,40,5.0,1,2.0,1,1,0,0,1.0,1,0,0,0,0,1,0,0,0,0,0,1
2223,2224,24,54,6,100,15.0,1,0.0,0,1,30,1,0.0,0,0,0,0,0,0,0,0,0,0,1,0
2736,2737,20,40,4,100,22.0,1,1.0,0,1,5,1,0.0,1,0,0,0,0,0,0,0,0,1,0,0
1625,1626,38,38,5,100,4.8,1,2.0,1,1,0,0,0.0,1,0,0,0,0,1,0,0,0,0,0,1

In [13]:
X_train.shape

(3903, 25)

In [14]:
#check if sum is 0 for any column to see if it is redundant
for col in X.columns:
    print(col, sum(X[col]))

id 11963005
region 9000
village 128822
age 247331
agpop 24388
rice_inc 360550
ricearea_2010 63102.949999296696
general_trust 4370
educ 5761.0
educ_good 1771
male 4264
disaster_loss 88685
disaster_yes 3159
risk_averse 925.5999934822321
literacy 3690
age_missing 0
agpop_missing 6
rice_inc_missing 73
ricearea_2010_missing 30
disaster_loss_missing 1904
educ_missing 0
male_missing 2
literacy_missing 0

In [15]:
test = pd.read_csv('insurance_prediction_to_predict.csv')
print(sum(test.educ_missing))
print(sum(test.literacy_missing))

152
152

In [16]:
X_train = X_train.drop(columns = ['literacy_missing', 'educ_missing', 'age_missing'])

In [17]:
X_train.corr()

,id,village,age,agpop,rice_inc,ricearea_2010,general_trust,educ,educ_good,male,disaster_loss,disaster_yes,risk_averse,literacy,agpop_missing,rice_inc_missing,ricearea_2010_missing,disaster_loss_missing,male_missing,region_1,region_2,region_3
id,1.000000,0.011228,-0.006320,0.000071,0.010862,-0.003372,0.024282,0.016183,0.017920,-0.025295,0.025651,0.019978,0.001053,0.003815,0.026374,0.008142,0.014129,-0.028034,-0.007613,-0.042153,-0.003863,0.050976
village,0.011228,1.000000,0.039200,0.063080,-0.065339,-0.023621,-0.024569,0.003450,-0.021062,0.135781,-0.085689,-0.062482,0.038050,0.051359,0.016896,-0.012691,0.007210,0.072934,-0.011295,0.164283,-0.100414,-0.078605
age,-0.006320,0.039200,1.000000,0.123659,-0.027331,-0.191429,0.051933,-0.341130,-0.320046,0.107932,-0.061797,-0.166481,-0.107621,-0.305862,0.001029,-0.018379,0.006321,0.142560,-0.010747,0.166642,-0.197348,0.019557
agpop,0.000071,0.063080,0.123659,1.000000,-0.115065,0.018305,0.001060,-0.008838,-0.000862,0.002999,-0.003274,-0.008805,-0.008444,-0.042397,0.000080,0.024836,0.046677,0.020745,-0.010445,0.069952,-0.081041,0.006337
rice_inc,0.010862,-0.065339,-0.027331,-0.115065,1.000000,0.216766,-0.013561,-0.130320,-0.083376,-0.083384,0.089910,0.179964,-0.068066,-0.091567,0.007034,0.028131,0.049459,-0.165899,0.013174,-0.209727,0.276966,-0.054343
ricearea_2010,-0.003372,-0.023621,-0.191429,0.018305,0.216766,1.000000,0.024066,0.066268,0.054080,0.017173,0.016307,0.129300,0.088081,0.093393,-0.004581,-0.012429,-0.012159,-0.049694,0.041248,-0.038524,0.134432,-0.096862
general_trust,0.024282,-0.024569,0.051933,0.001060,-0.013561,0.024066,1.000000,0.026706,0.007548,-0.060959,0.011905,-0.022491,0.016051,0.022229,0.011078,-0.001771,0.029400,0.012865,-0.065467,-0.077687,0.014378,0.071593
educ,0.016183,0.003450,-0.341130,-0.008838,-0.130320,0.066268,0.026706,1.000000,0.850171,0.286626,-0.061822,0.009535,0.125468,0.761483,0.066504,0.066687,-0.044928,0.009196,-0.004595,0.016235,0.025749,-0.044859
educ_good,0.017920,-0.021062,-0.320046,-0.000862,-0.083376,0.054080,0.007548,0.850171,1.000000,0.184681,-0.028445,0.025785,0.103665,0.423721,0.042875,0.069688,-0.025512,-0.010269,-0.016915,-0.051300,0.061281,-0.006570
male,-0.025295,0.135781,0.107932,0.002999,-0.083384,0.017173,-0.060959,0.286626,0.184681,1.000000,-0.109665,-0.064450,0.057243,0.331074,0.012136,0.017852,-0.031929,0.092188,0.008579,0.270170,-0.225662,-0.066335
disaster_loss,0.025651,-0.085689,-0.061797,-0.003274,0.089910,0.016307,0.011905,-0.061822,-0.028445,-0.109665,1.000000,0.640800,-0.080741,-0.068473,0.032872,-0.056418,-0.036166,-0.694428,0.012536,-0.317530,0.122074,0.226801
disaster_yes,0.019978,-0.062482,-0.166481,-0.008805,0.179964,0.129300,-0.022491,0.009535,0.025785,-0.064450,0.640800,1.000000,-0.079890,0.017329,0.023755,-0.006986,-0.057511,-0.847464,0.016793,-0.281821,0.243946,0.060302
risk_averse,0.001053,0.038050,-0.107621,-0.008444,-0.068066,0.088081,0.016051,0.125468,0.103665,0.057243,-0.080741,-0.079890,1.000000,0.118882,0.001046,-0.012575,0.002775,0.095428,-0.013616,0.047393,-0.004686,-0.047924
literacy,0.003815,0.051359,-0.305862,-0.042397,-0.091567,0.093393,0.022229,0.761483,0.423721,0.331074,-0.068473,0.017329,0.118882,1.000000,0.018167,0.034748,-0.050828,0.004462,0.012843,0.079244,-0.013467,-0.074275
agpop_missing,0.026374,0.016896,0.001029,0.000080,0.007034,-0.004581,0.011078,0.066504,0.042875,0.012136,0.032872,0.023755,0.001046,0.018167,1.000000,-0.004103,-0.002723,-0.025733,-0.000725,-0.027468,0.048129,-0.019444
rice_inc_missing,0.008142,-0.012691,-0.018379,0.024836,0.028131,-0.012429,-0.001771,0.066687,0.069688,0.017852,-0.056418,-0.006986,-0.012575,0.034748,-0.004103,1.000000,0.181837,0.030346,-0.002900,0.034158,-0.049976,0.013912
ricearea_2010_missing,0.014129,0.007210,0.006321,0.046677,0.049459,-0.012159,0.029400,-0.044928,-0.025512,-0.031929,-0.036166,-0.057511,0.002775,-0.050828,-0.002723,0.181837,1.000000,0.049846,-0.001925,-0.048324,0.035581,0.016837
disaster_loss_missing,-0.028034,0.072934,0.142560,0.020745,-0.165899,-0.049694,0.012865,0.009196,-0.010269,0.092188,-0.694428,-0.847464,0.095428,0.004462,-0.025733,0.030346,0.049846,1.000000,-0.018191,0.358077,-0.303696,-0.083125
male_missing,-0.007613,-0.011295,-0.010747,-0.010445,0.013174,0.041248,-0.065467,-0.004595,-0.016915,0.008579,0.012536,0.016793,-0.013616,0.012843,-0.000725,-0.002900,-0.001925,-0.018191,1.000000,0.026403,-0.015069,-0.013745
region_1,-0.042153,0.164283,0.166642,0.069952,-0.209727,-0.038524,-0.077687,0.016235,-0.051300,0.270170,-0.317530,-0.281821,0.047393,0.079244,-0.027468,0.034158,-0.048324,0.358077,0.026403,1.000000,-0.570713,-0.520595
region_2,-0.003863,-0.100414,-0.197348,-0.081041,0.276966,0.134432,0.014378,0.025749,0.061281,-0.225662,0.122074,0.243946,-0.004686,-0.013467,0.048129,-0.049976,0.035581,-0.303696,-0.015069,-0.570713,1.000000,-0.403991
region_3,0.050976,-0.078605,0.019557,0.006337,-0.054343,-0.096862,0.071593,-0.044859,-0.006570,-0.066335,0.226801,0.060302,-0.047924,-0.074275,-0.019444,0.013912,0.016837,-0.083125,-0.013745,-0.520595,-0.403991,1.000000

So educ_missing and literacy_missing have zero values in training data so do we remove them? But 152, nonzero values in test

In [18]:
model = XGBClassifier(random_state=1)

In [19]:
params = {
    'learning_rate': [0, 0.02, 0.05, 0.07, 0.1],
    'n_estimators': [150, 175, 200, 225, 250],
    'gamma': [0.4, 0.5, 0.6, 0.7],
    'subsample': [0.9, 0.925, 0.95, 0.975],
    'colsample_bytree': [0.9, 0.925, 0.95, 0.975],
    'max_depth': [35, 40, 45, 50, 55]
}

In [20]:
# Dataset will be divided into 5 folds (or subsets). 
# During cross-validation, the model will be trained and evaluated 5 times
# Data will be randomly shuffled before splitting into folds.
skf = StratifiedKFold(n_splits=5, shuffle = True, random_state = 1001)

In [21]:
random_search = RandomizedSearchCV(model, param_distributions=params, n_iter=500, scoring='neg_log_loss', n_jobs=4, cv=skf.split(X_train,y_train))

In [ ]:
random_search.fit(X_train,y_train)

In [ ]:
best_params = random_search.best_params_
best_params

In [ ]:
X_test = one_hot_encode(X_test, 'region')
#X_test = one_hot_encode(X_test, 'village')
X_test = X_test.drop(columns = ['literacy_missing', 'educ_missing', 'age_missing'])

In [ ]:
y_pred = random_search.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

In [ ]:
log_loss_score = log_loss(y_test, random_search.predict_proba(X_test))
log_loss_score #y_test (20% of training dataset given)

In [ ]:
test = pd.read_csv('insurance_prediction_to_predict.csv')

In [ ]:
X.educ_missing.sum()

In [ ]:
test.educ_missing.sum()

In [ ]:
test = one_hot_encode(test, 'region')
#test = one_hot_encode(test, 'village')
test = test.drop(columns = ['literacy_missing', 'educ_missing', 'age_missing'])

In [ ]:
results = random_search.predict_proba(test)

In [ ]:
results

In [ ]:
len(results)

In [ ]:
random_search.predict(test)

In [ ]:
results_dict = {
    'id': test.id,
    'takeup': results[:,1]
}

In [ ]:
results_df = pd.DataFrame(results_dict)

In [ ]:
results_df.to_csv('submission_xgb_ohe_region.csv', header = True, index = False)